insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('gmcquillen0', 'Gare', 'McQuillen', '10/11/2001', 'dN3,8MLiVAvkR"(');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('jgodwyn1', 'Jacqui', 'Godwyn', '8/11/2009', 'qK8<.2xLt/nU');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('cbuckerfield2', 'Charis', 'Buckerfield', '1/17/2008', 'wU2''_,BG5I4$#v*');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('glipmann3', 'Gaile', 'Lipmann', '5/18/2009', 'lY9{`?WMeX59W..8');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('dscullard4', 'Dov', 'Scullard', '8/23/2001', 'eC9)+B<Y');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('wfancet5', 'Wilona', 'Fancet', '1/9/2015', 'bA0!i`@5JX7t8DS');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('bcramb6', 'Barnaby', 'Cramb', '5/16/2006', 'jY8_yztjCE{2v/E');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('abecket7', 'Angy', 'Becket', '3/6/2014', 'aG3&2~@H<I');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('stollerfield8', 'Skippie', 'Tollerfield', '3/24/2004', 'hD5>Z7~LtMK@H');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('lluis9', 'Lillis', 'Luis', '5/2/2007', 'nC6#N!PH+PV@');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('ldewsnapa', 'Lucie', 'Dewsnap', '11/26/2014', 'tO7~}jybLDQCsB9x');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('cfoxtonb', 'Cecilla', 'Foxton', '9/26/2003', 'uD4!C*d1!mkRiEp+');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('abradfieldc', 'Avis', 'Bradfield', '8/7/2015', 'kH7?VK4f%zm{r2$');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('umartlandd', 'Udell', 'Martland', '4/21/2004', 'aQ3=HHT)');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('kdonsone', 'Kanya', 'Donson', '10/27/2010', 'zK5$L6o)\GEyUk');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hbellwardf', 'Hugo', 'Bellward', '1/10/2001', 'qN9(34J!MX@x9');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('mgaydeng', 'Marcella', 'Gayden', '11/20/2002', 'rE4@b&,f');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('lforderh', 'Leese', 'Forder', '1/29/2015', 'dA5(+uc9');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('jpenswicki', 'Jayme', 'Penswick', '11/9/2009', 'dW3%/YLR>D!<xOU');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('rwinfredj', 'Rosemary', 'Winfred', '3/21/2014', 'wF6!,rh@Ya}');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('gschindlerk', 'Genovera', 'Schindler', '8/23/2006', 'sV5~c<Vz!''%UeGD');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('jgilloranl', 'Jori', 'Gilloran', '4/5/2013', 'kB8!!Eae="I');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('adovinsonm', 'Arnie', 'Dovinson', '3/3/2002', 'zC1.K"Q4c');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('moadesn', 'Mandi', 'Oades', '5/6/2012', 'hB2%#C{|S');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hslideo', 'Henriette', 'Slide', '12/24/2013', 'gD2|"Yp)5,WC');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('phollyarp', 'Persis', 'Hollyar', '9/16/2001', 'bV1,5"OTfKZWj@)');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('dbarfieldq', 'Dalston', 'Barfield', '12/21/2002', 'bP4@sJu*?4');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('kaiskriggr', 'Kelley', 'Aiskrigg', '10/24/2006', 'mF5}Ry<kE4DyZ}');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('fopdenorths', 'Farlee', 'Opdenorth', '11/17/2010', 'gO9+5qxWA"bq`V|g');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('vmcilvorayt', 'Vick', 'McIlvoray', '3/3/2003', 'kY1?/EJRpmR3');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('koxladeu', 'Kele', 'Oxlade', '8/27/2010', 'gR1/EY_gz>o');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('dbenmorev', 'Druci', 'Benmore', '9/8/2001', 'cP5,bEp@*.(');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('nbinesteadw', 'Niki', 'Binestead', '10/12/2012', 'wM0/cG|mD8OF');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('bshearax', 'Blair', 'Sheara', '10/23/2007', 'aN1|)+#h~FME@}');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('lscarffy', 'Leandra', 'Scarff', '12/3/2011', 'sV5}Z2fLl4k+/');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('dsmedleyz', 'Ddene', 'Smedley', '1/20/2008', 'sK2.0*~jF');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('vleeman10', 'Vinnie', 'Leeman', '9/2/2011', 'tS7)V''Z#L~+\PHW');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('ctybalt11', 'Celestine', 'Tybalt', '4/9/2008', 'wX9\uW>S)R\)7zI');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('afoy12', 'Aylmer', 'Foy', '12/4/2011', 'bT0_+r\uF,0zCY');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('gvettore13', 'Godfree', 'Vettore', '2/18/2010', 'wH4{\xKj1');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('csibery14', 'Clevey', 'Sibery', '10/26/2003', 'jB4"e">K');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('bgodleman15', 'Bar', 'Godleman', '11/21/2006', 'dI0_.m/r~y9i(xS');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('mfeifer16', 'Mariya', 'Feifer', '4/6/2011', 'iF6\Ku<>=oHr');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('wrosencwaig17', 'Wood', 'Rosencwaig', '5/28/2012', 'cC3`M@0@wjr9');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('acurle18', 'Aloysius', 'Curle', '2/6/2006', 'kJ6+(S?|{8zX&cM');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('amilbank19', 'Anatol', 'Milbank', '8/29/2015', 'rX5<ttf5eI''`w');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hkincla1a', 'Hildagarde', 'Kincla', '1/28/2009', 'bI1+<T4f`#%');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('sbuntine1b', 'Sigismond', 'Buntine', '4/8/2001', 'rD1/_bR/#)');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('amardling1c', 'Abba', 'Mardling', '7/5/2012', 'sD2&BO3%');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('ppaybody1d', 'Patten', 'Paybody', '8/28/2002', 'iG0>(&\1Nilm5&');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('fnunn1e', 'Fields', 'Nunn', '4/1/2003', 'wJ5+By|`TO+h0Ma');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('nladds1f', 'Natty', 'Ladds', '2/9/2003', 'pH6=#+RPnz@');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('grobertshaw1g', 'Gary', 'Robertshaw', '2/14/2012', 'xZ1+DPl*''5''');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('fhavill1h', 'Falkner', 'Havill', '4/26/2014', 'zR1@~`BiqVKsJ');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('achomicki1i', 'Alonso', 'Chomicki', '10/21/2014', 'mC7?.U0&?');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('dlaxson1j', 'Dorri', 'Laxson', '5/3/2003', 'gT2&PMkWuL+Lmk)');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('mtapp1k', 'Magda', 'Tapp', '4/27/2013', 'cF0}=WU2X');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('eiacomini1l', 'Eward', 'Iacomini', '9/13/2010', 'zS7`m0j$V=S');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('mayars1m', 'Morly', 'Ayars', '3/27/2002', 'gY4{D%_k4MT');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('whowroyd1n', 'Willdon', 'Howroyd', '3/14/2013', 'uA9"c\?J`&|FJeu');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('nhusby1o', 'Nap', 'Husby', '6/6/2009', 'tU9{pdG~c');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hklaus1p', 'Humfrid', 'Klaus', '12/13/2001', 'xK9)qhU/yfD|');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('cdibling1q', 'Cassius', 'Dibling', '3/4/2004', 'lK1#o9$1(s');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('mfilgate1r', 'Martynne', 'Filgate', '1/5/2014', 'jK2&.B.j');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('pmacgaughey1s', 'Pavla', 'MacGaughey', '10/19/2013', 'lI4?dYQRW');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hcostan1t', 'Hayyim', 'Costan', '11/8/2010', 'bM9+VNH)h>');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('kmarsters1u', 'Kirbee', 'Marsters', '3/16/2009', 'uH2+Weajytwe4YU');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('akentish1v', 'Arvin', 'Kentish', '10/7/2004', 'dI4,\&$1');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('syeskov1w', 'Shamus', 'Yeskov', '5/22/2006', 'rI8\37<|a4AI');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('tgiocannoni1x', 'Tad', 'Giocannoni', '8/6/2006', 'bA6\y3o0%<');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('flago1y', 'Francklin', 'Lago', '12/1/2000', 'wE7+\0A\$');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('lmcleoid1z', 'Linette', 'McLeoid', '5/22/2008', 'oJ4?sn5Jy7huz~');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('srothschild20', 'Shanda', 'Rothschild', '2/22/2007', 'gV6,9DLQO@(I#');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('leaves21', 'Laura', 'Eaves', '9/13/2009', 'zM9{2&x*');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('gconry22', 'Gilli', 'Conry', '4/23/2009', 'vO0{b(utKRb*!@c');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('leldon23', 'Lenee', 'Eldon', '10/13/2009', 'uV0>}}310Z)z?');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('moldroyd24', 'Mead', 'Oldroyd', '8/14/2014', 'bO1"Y&Popx6wLLv1');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hcrumbleholme25', 'Hedda', 'Crumbleholme', '7/8/2011', 'sX2_WOUF*_B');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('ctupman26', 'Cher', 'Tupman', '4/7/2003', 'eO1**IW>6y#FS');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('rpizey27', 'Roxy', 'Pizey', '7/27/2013', 'cX3%l42B''m>_');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('lscolding28', 'Lila', 'Scolding', '9/21/2012', 'oZ9}P"oXTI#1Fd+');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('sgullifant29', 'Sibel', 'Gullifant', '5/26/2007', 'jB2&9Y3U8{Ww2');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('bnelsey2a', 'Barnebas', 'Nelsey', '1/27/2008', 'oV4<GwtS*J1OJ!');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('ohassin2b', 'Ozzie', 'Hassin', '10/3/2013', 'qR1.HH?Zsz');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hnaish2c', 'Helenelizabeth', 'Naish', '7/22/2008', 'tR4>*|.9pxie');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('pbleackly2d', 'Pandora', 'Bleackly', '11/1/2001', 'dM8!f{uh');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('fledley2e', 'Filbert', 'Ledley', '1/20/2010', 'xT3$n<|3C2R');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('obenley2f', 'Osbourne', 'Benley', '9/23/2014', 'wB8/*`=''00{+');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('slibbis2g', 'Sibeal', 'Libbis', '10/15/2007', 'tL6}+l9hJ=');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('abrosenius2h', 'Arlena', 'Brosenius', '1/27/2015', 'pH4%pd#N>LSD+IT');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('dwawer2i', 'Dulcea', 'Wawer', '12/10/2001', 'tC7&''se_f}');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('ckhomich2j', 'Cynthia', 'Khomich', '11/2/2000', 'bW8=kz?6l');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('datley2k', 'Didi', 'Atley', '5/24/2008', 'nN3~gR,4Kd}K9Mf');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('nosheerin2l', 'Norry', 'O''Sheerin', '7/28/2010', 'tM9{gO\Y?ze~mS');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('ldorn2m', 'Lynette', 'Dorn', '7/22/2012', 'yW1(h,M1g"{Np"O');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('mtidmarsh2n', 'Mannie', 'Tidmarsh', '4/28/2010', 'tT8*)J8Qz=C5?t');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('hboult2o', 'Hercule', 'Boult', '3/19/2014', 'hN3&jtBORt/.');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('jmissington2p', 'Judye', 'Missington', '2/22/2003', 'eK6*UDE\');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('zquogan2q', 'Zonda', 'Quogan', '3/30/2002', 'mG3+TY}Qx,Q');
insert into Users (Username, FirstName, LastName, DateOfBirth, Password) values ('rmicklem2r', 'Reube', 'Micklem', '11/14/2002', 'hQ3''aiAp_B7PC');



insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (100, 46, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (14, 17, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (84, 1, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (72, 61, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (11, 6, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 95, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (66, 87, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (46, 79, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (23, 36, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (65, 64, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (39, 64, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (57, 48, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (13, 45, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (37, 7, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (65, 76, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (100, 71, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (53, 73, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (89, 57, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (38, 7, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (6, 5, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (89, 9, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (32, 15, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (5, 87, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (41, 67, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (91, 47, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (21, 4, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (47, 1, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (20, 52, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (59, 29, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 42, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (90, 4, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (41, 94, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (3, 93, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (9, 43, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (1, 87, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (55, 26, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (40, 78, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (59, 21, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (28, 79, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (11, 20, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (55, 70, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (57, 83, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (42, 22, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (51, 88, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (91, 30, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (100, 21, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (34, 29, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (59, 38, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (73, 78, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (66, 15, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (69, 90, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (95, 92, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (97, 40, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (21, 26, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (30, 43, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (13, 20, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (36, 49, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (71, 96, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (20, 41, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (78, 27, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 36, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (64, 70, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (100, 83, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (19, 26, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (52, 5, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (19, 19, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (79, 3, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (64, 47, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (56, 75, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (51, 45, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (69, 44, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (10, 83, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (10, 9, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (16, 91, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (61, 37, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (43, 90, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (80, 68, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (94, 88, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (16, 18, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (51, 79, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (18, 99, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (6, 80, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (2, 75, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (64, 41, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (35, 78, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (77, 29, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (81, 13, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (61, 27, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (63, 4, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (27, 25, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (76, 86, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (61, 83, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (33, 90, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (48, 28, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (76, 68, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (79, 91, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (95, 95, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (75, 54, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (94, 80, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (51, 43, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (36, 1, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (34, 7, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (66, 35, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (7, 43, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (15, 60, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (55, 80, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (23, 42, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (72, 27, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (25, 16, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (86, 89, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (31, 3, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (76, 88, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (8, 30, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (64, 16, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (58, 74, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (41, 24, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (36, 43, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (25, 90, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (33, 92, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (83, 6, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (35, 56, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 62, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (21, 82, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (48, 5, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (30, 41, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (81, 71, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 4, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (53, 94, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (48, 8, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (59, 38, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (3, 3, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (86, 51, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (53, 70, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (47, 54, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (21, 33, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (83, 69, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (32, 59, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (35, 71, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (40, 54, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (33, 31, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (55, 88, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 73, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 6, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (31, 67, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (56, 68, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (29, 20, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (77, 85, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (79, 77, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (85, 94, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (75, 75, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (41, 55, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (54, 80, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (94, 33, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (43, 60, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (98, 3, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (2, 10, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (85, 19, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (95, 58, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (93, 21, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (97, 7, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (33, 66, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (25, 30, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (7, 34, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (52, 50, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (9, 1, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (31, 91, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (97, 80, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (44, 35, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (99, 20, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (33, 99, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (7, 77, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (91, 67, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (20, 79, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (75, 5, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (41, 24, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (1, 1, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (3, 19, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (92, 12, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (28, 47, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (58, 82, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (41, 87, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (78, 55, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (99, 7, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (54, 86, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (30, 49, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (65, 47, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (16, 18, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (95, 87, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (69, 78, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (16, 59, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (68, 73, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (78, 92, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (46, 85, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (75, 56, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (11, 27, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (45, 87, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (20, 7, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (59, 34, false);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (75, 7, true);
insert into Friends (FriendWhoAdded, FriendBeingAdded, IsAccepted) values (76, 88, true);



INSERT INTO Groups (GroupName, CreatedBy)
VALUES
('The Innovators Collective', 1),
('Campus Visionaries', 2),
('Trailblazers Club', 3),
('Quantum Thinkers Society', 4),
('The Idea Forge', 5),
('Future Leaders Network', 6),
('Synergy Circle', 7),
('The Next Gen Forum', 8),
('Inspire and Ignite Club', 9),
('The Creative Cohort', 10),
('Pioneers of Progress', 11),
('Dynamic Minds Association', 12),
('The Change Makers', 13),
('Visionary Voices Collective', 14),
('The Catalyst Crew', 15),
('The Vision Quest Club', 16),
('Empowerment Ensemble', 17),
('Innovative Minds Guild', 18),
('The Horizon Seekers', 19),
('The Renaissance Network', 20);

